### ISSUE TITLE
Metrics not flushed for generator functions

### ISSUE THREAD

**Issue by acradu** [awslabs/aws-embedded-metrics-python#112]
Hello,
I recently discovered that the metrics I was emitting from some generator functions were not actually being emitted and after some digging I found that the reason is that `@metric_scope` [doesn't actually iterate the generator](https://github.com/awslabs/aws-embedded-metrics-python/blob/master/aws_embedded_metrics/metric_scope/__init__.py#L44-L50), so `logger.flush()` occurs before any consumer attempts to use the generator.

Is this expected behavior or actually a bug?

**Comment by SamStephens** [comment]
My team is looking at lambda streaming using a custom runtime (as the Python runtime does not support streaming). The lack of this feature means `aws-embedded-metrics` cannot be used for streaming, where the streamed response is provided by a generator function.

**Comment by acradu** [comment]
#113 merged
