### ISSUE TITLE
Allow namespace to be specifiable via environment variables

### ISSUE THREAD

**Issue by pbhasker** [awslabs/aws-embedded-metrics-python#15]
I would like to be able to configure the metrics namespace via environment variables.

**Comment by jaredcnance** [comment]
This is a good suggestion. It’s pretty straightforward to implement if you would like to open a PR.

- update [environment_configuration_provider](https://github.com/awslabs/aws-embedded-metrics-python/blob/master/aws_embedded_metrics/config/environment_configuration_provider.py)
- update [metrics_context](https://github.com/awslabs/aws-embedded-metrics-python/blob/master/aws_embedded_metrics/logger/metrics_context.py) to consider the configuration parameter
- update README
