### ISSUE TITLE
[Question] How often is the PutMetricData

### ISSUE THREAD

**Issue by danketrotzdem** [awslabs/aws-embedded-metrics-python#17]
Hi, 

how often is PutMetricData called. Everytime a log has been written? I am asking because this is relevant for pricing. 

Best,
Patrick

**Comment by jaredcnance** [comment]
Your metrics don't go through the `PutMetricData` API and you are not charged for `PutMetricData` API calls. Total pricing includes log ingestion ($/GB) and metrics ($/metric/month).
