### ISSUE TITLE
MAX_DIMENSIONS should be 9, not 10

### ISSUE THREAD

**Issue by dlenski** [awslabs/aws-embedded-metrics-python#19]
Per [the upstream docs](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Embedded_Metric_Format_Specification.html#CloudWatch_Embedded_Metric_Format_Specification_structure_dimensionset):

> A DimensionSet MUST NOT contain more than 9 dimension keys.

Currently, you're setting `MAX_DIMENSIONS` to 10:

https://github.com/awslabs/aws-embedded-metrics-python/blob/658b2ebe829853a0ad53675d4b9d8917f7de18b7/aws_embedded_metrics/constants.py#L15

… and then using that to truncate the dimension set to 10 entries when serializing, e.g.:

https://github.com/awslabs/aws-embedded-metrics-python/blob/658b2ebe829853a0ad53675d4b9d8917f7de18b7/aws_embedded_metrics/serializers/log_serializer.py#L23-L30

I'm not sure that “silently truncating the dimension set” to an acceptable size is the best solution, but in any case the `MAX_DIMENSIONS` should be reduced to 9.

**Comment by jaredcnance** [comment]
Thanks for reporting this! Definitely open to proposals on how to treat this. I've considered adding a configuration parameter that would throw exceptions or to log and silently move on in these kinds of cases.

**Comment by dlenski** [comment]
Based on the [Zen of Python](https://en.wikipedia.org/wiki/Zen_of_Python) (“Explicit is better than implicit”, “Errors should never pass silently unless explicitly silenced”, and all that) I would say that throwing an exception is probably the right default behavior.
