### ISSUE TITLE
Unable to override LogGroupName in Lambda

### ISSUE THREAD

**Issue by charliejllewellyn** [awslabs/aws-embedded-metrics-python#33]
Despite having set:

```
from aws_embedded_metrics.config import get_config
Config = get_config()
Config.log_group_name = "testLogGroup"
```

It defaults to the lambda function name.

This looks to be set in lambda_environment.py to only return the Lambda function name:

```
    def get_log_group_name(self) -> str:
        return get_env("AWS_LAMBDA_FUNCTION_NAME")\
```

Would be nice to be able to override this.

**Comment by jaredcnance** [comment]
Unfortunately, there is no way to change the LogGroup on Lambda functions today. It is controlled by the Lambda platform. This setting only applies to environments using the CWAgent.
