### ISSUE TITLE
Allow ability to set custom Timestamp

### ISSUE THREAD

**Issue by MattWilliams89** [awslabs/aws-embedded-metrics-python#59]
We have a use-case where events could be batched up and send _some time_ later. (Think offline mobile application).
We'd like some mechanism to emit a timestamp from our client which could then be translated to the timestamp on the event sent to AWS. In a similar way to how we set properties/dimensions, we'd like to be able to specify the timestamp.

**Comment by jaredcnance** [comment]
The Timestamp is set here:

https://github.com/awslabs/aws-embedded-metrics-python/blob/8878b3b333f8b110fa706eb712667a88758f78f4/aws_embedded_metrics/logger/metrics_context.py#L40

We would need to add a method on the logger to update it.

**Comment by mlartz** [comment]
We have a similar use-case, in that we'd like to set the metric based on some timestamp from our source data, instead of the processing time.  Is it "safe" to reach into `meta` and change this timestamp manually?

**Comment by jaredcnance** [comment]
It is certainly “safe” in the current version. However we should provide a public API to reduce the risk of breaking changes
