### ISSUE TITLE
Is this project still actively supported?

### ISSUE THREAD

**Issue by ssoper-usgs** [awslabs/aws-embedded-metrics-python#75]
I am curious about using this tool, is it stable and still being worked on? I am trying to assess how risky it would be/how much support it has if I were to implement it on a high throughput python project.  Thanks!

**Comment by SamStephens** [comment]
Doesn't look encouraging does it?

Pretty disappointing as this package is directly recommended from AWS documentation.

**Comment by markkuhn** [comment]
Hello @ssoper-usgs @SamStephens. Yes, this project is actively maintained and being worked on.
