### ISSUE TITLE
Disallow duplicate dimension sets

### ISSUE THREAD

**Issue by markkuhn** [awslabs/aws-embedded-metrics-python#83]
Related issues:
* https://github.com/awslabs/aws-embedded-metrics-node/issues/20
* https://github.com/awslabs/aws-embedded-metrics-node/pull/104
* https://github.com/awslabs/aws-embedded-metrics-java/pull/88
* https://github.com/awslabs/aws-embedded-metrics-dotnet/issues/31

Currently duplicate dimension sets are being allowed.
Example:
```python
metrics.put_dimensions({"Region": "us-east-1"})
metrics.put_dimensions({"Region": "us-east-2"})
```
This creates:
```json
"Dimensions": [
  [
    "LogGroup",
    "ServiceName",
    "ServiceType",
    "Region"
  ],
  [
    "LogGroup",
    "ServiceName",
    "ServiceType",
    "Region"
  ]
]
```
When it should be:
```json
"Dimensions": [
  [
    "LogGroup",
    "ServiceName",
    "ServiceType",
    "Region"
  ]
]
```

**Comment by gordonpn** [comment]
Should there be an issue for the dotnet library as well?

**Comment by markkuhn** [comment]
@gordonpn The dotnet library doesn't have this issue since it doesn't have a `putDimension` method. It only has a `setDimensions` method.
